from myproject.settings.common import *
import dj_database_url

# DEBUG CONFIG
DEBUG = True

# DATABASE CONFIG
DATABASES['default'] = dj_database_url.config()

# REDIS CONFIG
REDIS_URL = os.environ.get('REDIS_URL')
BROKER_CONNECTION_MAX_RETRIES = None
BROKER_POOL_LIMIT = None

# CELERY CONFIG
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_REDIS_MAX_CONNECTIONS = 5
CELERYD_CONCURRENCY = 1
